{% set name = "uftp" %}
{% set version = "5.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/uftp-multicast/files/source-tar/{{ name }}-{{ version }}.tar.gz
  sha256: cb8668c19b1f10bc63a16ffa893e205dc3ec86361037d477d8003260ebc40080
  patches:
    - 0001-install-to-bin.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - openssl

test:
  commands:
    - test -x ${PREFIX}/bin/uftp
    - test -x ${PREFIX}/bin/uftpd
    - test -x ${PREFIX}/bin/uftp_keymgt
    - test -x ${PREFIX}/bin/uftpproxyd

about:
  home: http://uftp-multicast.sourceforge.net/
  license: GPL-3.0+
  license_file: LICENSE.txt
  summary: Encrypted UDP based FTP with multicast

extra:
  recipe-maintainers:
    - asafkahlon
