{% set name = "uftp" %}
{% set version = "5.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/uftp-multicast/files/source-tar/{{ name }}-{{ version }}.tar.gz
  sha256: f0435fbc8e9ffa125e05600cb6c7fc933d7d587f5bae41b257267be4f2ce0e61
  patches:
    - 0001-install-to-bin.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - openssl

test:
  commands:
    - test -x ${PREFIX}/bin/uftp
    - test -x ${PREFIX}/bin/uftpd
    - test -x ${PREFIX}/bin/uftp_keymgt
    - test -x ${PREFIX}/bin/uftpproxyd

about:
  home: http://uftp-multicast.sourceforge.net/
  license: GPL-3.0+
  license_file: LICENSE.txt
  summary: Encrypted UDP based FTP with multicast

extra:
  recipe-maintainers:
    - asafkahlon
